[package]
name = "winit-vulkan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.72", features = ["backtrace"] }
ash = { version = "0.37.3", features = ["linked"] }
ash-window = "0.12.0"
console-subscriber = "0.2.0"
futures = "0.3.28"
log = "0.4.19"
raw-window-handle = "0.6.0"
simple_logger = {version = "4.2.0", default-features = false, features = ["colors"]}
thiserror = "1.0.44"
tokio = { version = "1.29.1", features = ["full", "tracing"] }
winit = "0.29.10"

