[package]
name = "winit-vulkan"
version = "0.1.0"
edition = "2021"

[lib]
crate_type=["cdylib", "rlib"]

[[bin]]
name = "winit-vulkan"

[dependencies]
android-activity = { version = "0.5.2", optional = true }
android_logger = { version = "0.13.3", optional = true }
anyhow = { version = "1.0.72", features = ["backtrace"] }
ash = { version = "0.37.3", features = ["linked"] }
ash-window = "0.12.0"
console-subscriber = "0.2.0"
futures = "0.3.28"
log = "0.4.19"
raw-window-handle = "0.5.0"
simple_logger = {version = "4.2.0", default-features = false, features = ["colors"]}
thiserror = "1.0.44"
tokio = { version = "1.29.1", features = ["full", "tracing"] }
winit = { version = "0.29.10", features = ["rwh_05", "android-native-activity"] }


[patch.crates-io]
android-activity = { git = "ssh://github.com/skibon02/android-activity.git" }

[features]
default = []
android = ["android-activity", "android_logger"]
